name: Release Attacher for client and server

on:
  release:
    types: [published]

jobs:
  release-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create archive client
        run: zip -r client_${{ github.event.release.tag_name }}.zip client/*

      - name: Attach archives to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client_${{ github.event.release.tag_name }}.zip
